spring.application.name=TpIntegrado
server.servlet.context-path=/market/api
server.port=${PORT:8080}


# Database (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:marketdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate (Auto create tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (Optional, accessible at /market/api/h2-console)
spring.h2.console.enabled=true

# Defer execution of data.sql until Hibernate creates the tables
spring.jpa.defer-datasource-initialization=true


# --- Configuración Original de MySQL (Comentada para usar H2) ---
# spring.datasource.url=jdbc:mysql://localhost:3306/market
# spring.datasource.username=root
# spring.datasource.password=123456
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
